"""v7: the recap provider job, the recap/notes-review templates, and the
categorized tn_generate.md rewrite.

Three skill changes land here at once. (1) A new `recap` provider job:
the rolling story-so-far recap (story_state.json, one <= 120-word entry
per translated chapter, injected into the next chapter's
[Background Information] frame) is generated by ONE recap-provider call
per chapter -- a job meant for a cheap model. (2) Two newly shipped
templates: recap.md (the recap generation prompt) and notes_review.md
(the `review notes` model tier's judgment prompt). (3) tn_generate.md was
rewritten: glossary-aware annotation (the prompt pins the glossary's
deliberate renderings), the cultural/idiom/wordplay/honorific/unit/other
categories, a code-enforced max_notes_per_chapter cap, and the
notes/<stem>.dropped.json review artifact for discarded candidates.

No config.json DEFAULTS key is added, removed, or renamed -- the only
schema change is the recap entry under "providers" -- so
materialize_config folds the block in through the established provider
normalization (user-set values always preserved; an omitted job inherits
the project's translator block, per the documented rule) and reports
"provider blocks normalized", like the no-new-keys case of v001. The
template side is sync_templates as in every step since v001: missing
copies are always added, drifted ones (every pre-v007 project's
tn_generate.md reads as drifted after the rewrite) only refreshed with
consent (--force silently, or the caller's confirm callback;
confirm=None non-interactively keeps the user's copy with a [warn]).
Idempotent like v001-v006 -- a project whose config is the merged form
and whose templates already match the shipped copies reports [].
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

from . import common

VERSION = 7
DESCRIPTION = ("materialize the recap provider job; ship recap.md and "
               "notes_review.md; refresh tn_generate.md")


def migrate(project_dir: Path, templates_src: Path,
            dry_run: bool = False, force: bool = False,
            confirm: Callable[[str], bool] | None = None) -> list[str]:
    return common.standard_step(project_dir, templates_src, dry_run, force, confirm)
